# This is the smtpd server system-wide configuration file.
# See smtpd.conf(5) for more information.

table aliases file:/etc/mail/aliases
table blocked file:/etc/mail/blocked

if = "{{ smtpd_if }}"

pki {{ smtpd_fqdn }} cert "{{ smtpd_tls_cert }}"
pki {{ smtpd_fqdn }} key "{{ smtpd_tls_key }}"

filter "dkimsign" proc-exec \
    "filter-dkimsign -d {{ smtpd_dkim_domain }} -s {{ smtpd_dkim_selector }} -k {{ smtpd_dkim_key }}" \
    user _dkimsign group _dkimsign

filter "rdns" phase connect match !fcrdns reject "RDNS unacceptable"

listen on socket
listen on lo0
listen on $if tls pki {{ smtpd_fqdn }} \
    filter "rdns"
listen on $if smtps pki {{ smtpd_fqdn }} \
    auth filter "dkimsign"
listen on $if tls-require pki {{ smtpd_fqdn }} port 587 \
    auth filter "dkimsign"

bounce warn-interval 15m, 1h, 4h

action "local" mbox alias <aliases>
action "relay" relay
action "maildir" maildir alias <aliases>

match mail-from regex <blocked> reject
{% for d in smtpd_deliver_domains %}
match for domain "{{ d }}" action "maildir"
{% endfor %}
match from any for local action "maildir"
match from local for any action "relay"
match auth from any for any action "relay"
