#!/bin/sh
# sshguard.conf -- SSHGuard configuration

BACKEND="/usr/local/libexec/sshg-fw-pf"
FILES=/var/log/authlog

# Block attackers when their cumulative attack score exceeds THRESHOLD.
# Most attacks have a score of 10. (optional, default 30)
THRESHOLD=20

# Initial block time in seconds, multiplied by 1.5 for each subsequent block
BLOCK_TIME=120

# How long to remember attackers
#DETECTION_TIME=1800

# Size of subnets to block (CIDR notation, default full address)
#IPV6_SUBNET=128
#IPV4_SUBNET=32

# When set, sandboxed processes drop permissions by changing to this user.
SSHGUARD_USER=nobody

PID_FILE=/var/run/sshguard.pid

# When set, write Prometheus-compatible statistics to .prom files in this
# directory every minute. These metrics can be exported using node_exporter's
# textfile collector.
# (Doesn't work on OpenBSD, seems to be not catching a signal, so I'll look at pushing a fix.)
#STATS_DIR="/var/metrics"
