all:
  hosts:
    main:
      ansible_user: ansible
      ansible_host: jacobedwards.org
      ansible_become_method: doas

  children:
    web:
      hosts:
        main:
    mail:
      hosts:
        main:
    monitoring:
      hosts:
        main:
