- name: Upgrade packages
  ansible.builtin.command:
    cmd: "pkg_add -u"
  tags: [runtime]

- name: Install system patches
  ansible.builtin.command:
    cmd: "syspatch"
  tags: [runtime]

- name: Install non-free firmware
  ansible.builtin.command:
    cmd: "fw_update"
  tags: [runtime]
