# relayd.conf

ext_if = "vio0"
spaceplanner_port = "3600"
gonic_port = "4747"
grafana_port = "3000"

table <httpd> { 127.0.0.1 }
table <spaceplanner_api> { 127.0.0.1 }
table <gonic> { 127.0.0.1 }
table <grafana> { 127.0.0.1 }

http protocol "http" {
	pass forward to <httpd>
}

http protocol "https" {
	tls { keypair "spaceplanner.app" \
	      keypair "jacobedwards.org" }
	pass request quick header "Host" value "api.spaceplanner.app" \
	    forward to <spaceplanner_api>
	pass request quick header "Host" value "music.jacobedwards.org" \
	    forward to <gonic>
	pass request quick header "Host" value "monitoring.jacobedwards.org" \
	    forward to <grafana>
	pass forward to <httpd>
}

relay "http" {
	listen on $ext_if port 80
	protocol "http"
	forward to <httpd> port 8080
}

relay "https" {
	listen on $ext_if port 443 tls
	protocol "https"
	forward to <spaceplanner_api> port $spaceplanner_port
	forward to <gonic> port $gonic_port
	forward to <grafana> port $grafana_port
	forward to <httpd> port 8443
}
