# pf.conf(5)

if = "vio0"

queue  main     on  $if bandwidth 1G
queue admin parent main bandwidth 10M min 5M burst 50M for 100ms
queue  data parent main bandwidth 500M
queue  data_prio parent data bandwidth 500M
queue  data_bulk parent data bandwidth 10M default

table <sshguard> persist counters

set skip on lo
block return

# Block from sshguard flagged attacks
block in quick on $if from <sshguard>

# WireGuard
set skip on wg0
pass out quick on egress from wg0:network to any nat-to (egress)
pass in quick proto udp from any to any port 4433

# Allow all outgoing by default
pass out on $if

# Allow ICMP
pass in on $if proto icmp \
	set queue admin

# Allow SSH
pass in on $if proto tcp to port ssh \
	set queue admin

# Allow mail
pass in quick on $if proto tcp to port {smtp, smtps, submission, imaps} \
	set queue data_bulk

# Allow web
pass in on $if proto tcp to port {http, https} \
	set queue data_prio

# Allow git (gitdaemon)
pass in on $if proto tcp to port git \
	set queue data_bulk

# Allow XMPP
pass in on $if proto tcp to port {xmpp-server, 5223, 5281, xmpp-client} \
	set queue data_prio

# Port build user does not need network
block return out log proto {tcp udp} user _pbuild
