- import_tasks: dkim.yml

- name: Install aliases
  ansible.builtin.template:
    src: aliases
    dest: /etc/mail/aliases
    owner: root
    group: wheel
    mode: 0644
  notify: newaliases
  tags: [config]

- name: Install blocked sources
  ansible.builtin.template:
    src: blocked
    dest: /etc/mail/blocked
    owner: root
    group: wheel
    mode: 0644
  notify: update blacklist
  tags: [config]

- name: Install smtpd.conf
  ansible.builtin.template:
    src: smtpd.conf
    dest: /etc/mail/smtpd.conf
    owner: root
    group: wheel
    mode: 0644
  notify: restart smtpd
  tags: [config]
