#alertmanager_smtp_key:
alertmanager_smtp_user: "_alertmanager"
alertmanager_smtp_from: "alerts <{{ alertmanager_smtp_user}}@{{ ansible_host }}>"
alertmanager_smtp_smarthost: "localhost:25"
alertmanager_receiver_email: "hostmaster@{{ ansible_host }}"
