# httpd.conf

internal = "127.0.0.1"

types {
        text/javascript mjs
	text/markdown	md
        include "/usr/share/misc/mime.types"
}

# jacobedwards.org

# acme challenge and https redirect for jacobedwards.org
server "*.jacobedwards.org" {
	listen on $internal port 8080
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}
	location * {
		block return 301 "https://$HTTP_HOST$REQUEST_URI"
	}
}

server "www.jacobedwards.org" {
	listen on $internal port 8080
	listen on $internal port 8443
	block return 301 "https://jacobedwards.org$REQUEST_URI"
}

server "jacobedwards.org" {
	listen on $internal port 8443
	root "/htdocs/jacobedwards.org"
	errdocs "/htdocs/jacobedwards.org"
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}
	location "/.well-known/caldav" {
		block return 301 "https://$HTTP_HOST/cgi-bin/kcaldav"
	}
	location "/caldav" {
		block return 301 "https://$HTTP_HOST/cgi-bin/kcaldav"
	}
	location "/cgi-bin/*" {
		fastcgi
		root "/"
	}
	location "/davical" {
		directory index index.php
	}
	location "/davical/*.php*" {
		fastcgi socket "/run/php-fpm.sock"
		root "/davical/htdocs/index.php"
		request strip 2
	}
	location "/projects/*/*" {
		directory index log.html
	}
}

server "dist.jacobedwards.org" {
	listen on $internal port 8443
	directory auto index
	root "/htdocs/dist.jacobedwards.org"
}

server "man.jacobedwards.org" {
	listen on $internal port 8443
	root "/htdocs/man.jacobedwards.org"
	fastcgi socket "/var/www/run/slowcgi.sock"
	location "/mandoc.css" {
		no fastcgi
	}
	location match "(.*)" {
		request rewrite "/man.cgi/%1"
	}
}

# spaceplanner.app

server "www.spaceplanner.app" {
	listen on $internal port 8443
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}
	root "/htdocs/www.spaceplanner.app"
}

# use www domain
server "spaceplanner.app" {
	listen on $internal port 8443
	listen on $internal port 8080
	block return 301 "https://www.spaceplanner.app/$DOCUMENT_URI"
}

# acme challenge and https redirect for spaceplanner.app
server "*.spaceplanner.app" {
	listen on $internal port 8080

	# Allow acme-challenge
	location "/.well-known/acme-challenge/*" {
		root "/acme"
		request strip 2
	}

	# Redirect everything else to https
	location * {
		block return 301 "https://$HTTP_HOST$REQUEST_URI"
	}
}
