- name: Upgrade system
  hosts: all
  become: true
  tasks:
    - name: Fetch upgrade if available
      ansible.builtin.command:
        cmd: "sysupgrade -n"
      register: sysupgrade_output
    
    - name: Set upgraded fact
      set_fact:
        upgraded: "{{ sysupgrade_output.stdout_lines[-1] == 'Already on latest release.' }}"

    - name: Cancel upgrade if already upgraded
      meta: end_play
      when: upgraded

    - name: Cancel anyway
      meta: end_play

    - name: Upgrade system
      ansible.builtin.reboot:
        reboot_timeout: 900

    - name: Include update role
      ansible.builtin.include_role:
        name: update

    - name: Merge configuration files
      ansible.builtin.command:
        cmd: "sysmerge -b"

    - name: Reboot system
      ansible.builtin.reboot:
